const apiBaseUrl = import.meta.env.VITE_API_BASE_URL ?? "/api";
export interface SegmentResponseDto { id: number; annotationSessionId: number; segmentNumber: number; startTime: string; endTime: string; transcript: string; submittedAt: string; }
export interface SegmentResponseRequest { annotationSessionId: number; segmentNumber: number; startTime: string; endTime: string; transcript: string; submittedAt?: string; }
function endpoint(path = "") { return `${apiBaseUrl}/segment-responses${path}`; }
function requestHeaders(): HeadersInit { const token = localStorage.getItem("annotate_pro_token"); return { "Content-Type": "application/json", ...(token ? { Authorization: `Bearer ${token}` } : {}) }; }
async function parseResponse<T>(response: Response): Promise<T> { const text = await response.text(); let body: T | { error?: string; message?: string } | undefined; try { body = text ? JSON.parse(text) : undefined; } catch { body = { message: text }; } if (!response.ok) { const details = body as { error?: string; message?: string } | undefined; throw new Error(details?.error ?? details?.message ?? `Request failed (${response.status}).`); } return body as T; }
const withSubmittedAt = (request: SegmentResponseRequest) => ({ ...request, submittedAt: request.submittedAt ?? new Date().toISOString() });
export async function getSegmentsBySession(sessionId: number) { const response = await fetch(endpoint("/"), { headers: requestHeaders() }); const rows = await parseResponse<SegmentResponseDto[]>(response); return rows.filter(row => row.annotationSessionId === sessionId); }
export async function createSegment(request: SegmentResponseRequest) { return parseResponse<SegmentResponseDto>(await fetch(endpoint("/"), { method: "POST", headers: requestHeaders(), body: JSON.stringify(withSubmittedAt(request)) })); }
export async function updateSegment(id: number, request: SegmentResponseRequest) { return parseResponse<SegmentResponseDto>(await fetch(endpoint(`/${id}`), { method: "PUT", headers: requestHeaders(), body: JSON.stringify(withSubmittedAt(request)) })); }
export async function deleteSegment(id: number) { const response = await fetch(endpoint(`/${id}`), { method: "DELETE", headers: requestHeaders() }); if (!response.ok) await parseResponse<never>(response); }
export function secondsToTimeSpan(totalSeconds: number) { const safe = Math.max(0, totalSeconds); const h = Math.floor(safe / 3600); const m = Math.floor((safe % 3600) / 60); const s = safe % 60; return `${String(h).padStart(2, "0")}:${String(m).padStart(2, "0")}:${s.toFixed(3).padStart(6, "0")}`; }
export function timeSpanToSeconds(value: string) { const parts = value.split(":").map(Number); return parts.length === 3 && !parts.some(Number.isNaN) ? parts[0] * 3600 + parts[1] * 60 + parts[2] : 0; }
