// <auto-generated />
using System;
using Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Context.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Context.Entities.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Username");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("Context.Entities.AnnotationSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnnotatorId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Assigned");

                    b.Property<int>("VideoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("AnnotatorId", "Status");

                    b.HasIndex("VideoId", "Status");

                    b.ToTable("AnnotationSessions", t =>
                        {
                            t.HasCheckConstraint("CK_AnnotationSessions_ExpiryAfterAssignment", "[ExpiresAt] > [AssignedAt]");

                            t.HasCheckConstraint("CK_AnnotationSessions_Status", "[Status] IN ('Assigned', 'InProgress', 'Completed', 'Expired', 'Cancelled')");
                        });
                });

            modelBuilder.Entity("Context.Entities.AnnotationTaskRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AnnotationSessionId")
                        .HasColumnType("int");

                    b.Property<int>("AnnotatorId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("DatasetId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("FulfilledAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Waiting");

                    b.HasKey("Id");

                    b.HasIndex("AnnotationSessionId")
                        .IsUnique()
                        .HasFilter("[AnnotationSessionId] IS NOT NULL");

                    b.HasIndex("Status");

                    b.HasIndex("AnnotatorId", "DatasetId", "Status")
                        .IsUnique()
                        .HasFilter("[Status] = 'Waiting'");

                    b.HasIndex("DatasetId", "Status", "RequestedAt");

                    b.ToTable("AnnotationTaskRequests", t =>
                        {
                            t.HasCheckConstraint("CK_AnnotationTaskRequests_Status", "[Status] IN ('Waiting', 'Fulfilled', 'Cancelled')");
                        });
                });

            modelBuilder.Entity("Context.Entities.Annotator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("HasCompletedSurvey")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Username");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Annotators");
                });

            modelBuilder.Entity("Context.Entities.AnnotatorSurvey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("AnnotatorId")
                        .HasColumnType("int");

                    b.Property<string>("DrivingFrequency")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("DrivingScenarioConstructionZone")
                        .HasColumnType("bit");

                    b.Property<bool>("DrivingScenarioHeavyRain")
                        .HasColumnType("bit");

                    b.Property<bool>("DrivingScenarioNighttime")
                        .HasColumnType("bit");

                    b.Property<bool>("DrivingScenarioNone")
                        .HasColumnType("bit");

                    b.Property<bool>("DrivingScenarioSnowyWeather")
                        .HasColumnType("bit");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("HasAccidentsInLastFiveYears")
                        .HasColumnType("bit");

                    b.Property<bool>("HasDriverLicense")
                        .HasColumnType("bit");

                    b.Property<bool>("HasPriorDatasetAnnotationExperience")
                        .HasColumnType("bit");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PrimaryDrivingCountry")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("YearsOfDrivingExperience")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AnnotatorId")
                        .IsUnique();

                    b.ToTable("AnnotatorSurveys");
                });

            modelBuilder.Entity("Context.Entities.Dataset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DatasetType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("ManifestFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("ManifestPath")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("IsArchived");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Datasets");
                });

            modelBuilder.Entity("Context.Entities.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("DatasetId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("Context.Entities.QuestionAnswer", b =>
                {
                    b.Property<int>("SegmentResponseId")
                        .HasColumnType("int");

                    b.Property<int>("QuestionNumber")
                        .HasColumnType("int");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SegmentResponseId", "QuestionNumber");

                    b.ToTable("QuestionAnswers");
                });

            modelBuilder.Entity("Context.Entities.SegmentResponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnnotationSessionId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<int>("SegmentNumber")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Transcript")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AnnotationSessionId", "SegmentNumber")
                        .IsUnique();

                    b.ToTable("SegmentResponses");
                });

            modelBuilder.Entity("Context.Entities.Video", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("DatasetId")
                        .HasColumnType("int");

                    b.Property<int?>("DatasetRowIndex")
                        .HasColumnType("int");

                    b.Property<string>("DrivingInstruction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("DurationSeconds")
                        .HasColumnType("float");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<double?>("FrameRate")
                        .HasColumnType("float");

                    b.Property<int?>("Height")
                        .HasColumnType("int");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("ManifestMatched")
                        .HasColumnType("bit");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OriginalReasoningJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProcessingError")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProcessingStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RequiredAnnotationCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("ScenarioId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ScenarioType")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("ThumbnailPath")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("TrajectoryJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("UploadedByAdminId")
                        .HasColumnType("int");

                    b.Property<int?>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IsArchived");

                    b.HasIndex("ScenarioId");

                    b.HasIndex("UploadedByAdminId");

                    b.HasIndex("DatasetId", "FileName")
                        .IsUnique()
                        .HasFilter("[DatasetId] IS NOT NULL");

                    b.HasIndex("IsArchived", "ProcessingStatus");

                    b.ToTable("Videos", t =>
                        {
                            t.HasCheckConstraint("CK_Videos_RequiredAnnotationCount_Positive", "[RequiredAnnotationCount] >= 1");
                        });
                });

            modelBuilder.Entity("Context.Entities.AnnotationSession", b =>
                {
                    b.HasOne("Context.Entities.Annotator", "Annotator")
                        .WithMany("AnnotationSessions")
                        .HasForeignKey("AnnotatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Context.Entities.Video", "Video")
                        .WithMany("AnnotationSessions")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Annotator");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("Context.Entities.AnnotationTaskRequest", b =>
                {
                    b.HasOne("Context.Entities.AnnotationSession", "AnnotationSession")
                        .WithOne()
                        .HasForeignKey("Context.Entities.AnnotationTaskRequest", "AnnotationSessionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Context.Entities.Annotator", "Annotator")
                        .WithMany("AnnotationTaskRequests")
                        .HasForeignKey("AnnotatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Context.Entities.Dataset", "Dataset")
                        .WithMany("AnnotationTaskRequests")
                        .HasForeignKey("DatasetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AnnotationSession");

                    b.Navigation("Annotator");

                    b.Navigation("Dataset");
                });

            modelBuilder.Entity("Context.Entities.AnnotatorSurvey", b =>
                {
                    b.HasOne("Context.Entities.Annotator", "Annotator")
                        .WithOne("Survey")
                        .HasForeignKey("Context.Entities.AnnotatorSurvey", "AnnotatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Annotator");
                });

            modelBuilder.Entity("Context.Entities.QuestionAnswer", b =>
                {
                    b.HasOne("Context.Entities.SegmentResponse", "SegmentResponse")
                        .WithMany("QuestionAnswers")
                        .HasForeignKey("SegmentResponseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SegmentResponse");
                });

            modelBuilder.Entity("Context.Entities.SegmentResponse", b =>
                {
                    b.HasOne("Context.Entities.AnnotationSession", "AnnotationSession")
                        .WithMany("SegmentResponses")
                        .HasForeignKey("AnnotationSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnnotationSession");
                });

            modelBuilder.Entity("Context.Entities.Video", b =>
                {
                    b.HasOne("Context.Entities.Dataset", "Dataset")
                        .WithMany("Videos")
                        .HasForeignKey("DatasetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Context.Entities.Admin", "UploadedByAdmin")
                        .WithMany("UploadedVideos")
                        .HasForeignKey("UploadedByAdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Dataset");

                    b.Navigation("UploadedByAdmin");
                });

            modelBuilder.Entity("Context.Entities.Admin", b =>
                {
                    b.Navigation("UploadedVideos");
                });

            modelBuilder.Entity("Context.Entities.AnnotationSession", b =>
                {
                    b.Navigation("SegmentResponses");
                });

            modelBuilder.Entity("Context.Entities.Annotator", b =>
                {
                    b.Navigation("AnnotationSessions");

                    b.Navigation("AnnotationTaskRequests");

                    b.Navigation("Survey");
                });

            modelBuilder.Entity("Context.Entities.Dataset", b =>
                {
                    b.Navigation("AnnotationTaskRequests");

                    b.Navigation("Videos");
                });

            modelBuilder.Entity("Context.Entities.SegmentResponse", b =>
                {
                    b.Navigation("QuestionAnswers");
                });

            modelBuilder.Entity("Context.Entities.Video", b =>
                {
                    b.Navigation("AnnotationSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
