// <auto-generated />
using System;
using Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Context.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Context.Entities.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("Context.Entities.AnnotationSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnnotatorId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("VideoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AnnotatorId");

                    b.HasIndex("VideoId");

                    b.ToTable("AnnotationSessions");
                });

            modelBuilder.Entity("Context.Entities.Annotator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Annotators");
                });

            modelBuilder.Entity("Context.Entities.QuestionAnswer", b =>
                {
                    b.Property<int>("SegmentResponseId")
                        .HasColumnType("int");

                    b.Property<int>("QuestionNumber")
                        .HasColumnType("int");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SegmentResponseId", "QuestionNumber");

                    b.ToTable("QuestionAnswers");
                });

            modelBuilder.Entity("Context.Entities.SegmentResponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnnotationSessionId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<int>("SegmentNumber")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Transcript")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AnnotationSessionId", "SegmentNumber")
                        .IsUnique();

                    b.ToTable("SegmentResponses");
                });

            modelBuilder.Entity("Context.Entities.Video", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("UploadedByAdminId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UploadedByAdminId");

                    b.ToTable("Videos");
                });

            modelBuilder.Entity("Context.Entities.AnnotationSession", b =>
                {
                    b.HasOne("Context.Entities.Annotator", "Annotator")
                        .WithMany("AnnotationSessions")
                        .HasForeignKey("AnnotatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Context.Entities.Video", "Video")
                        .WithMany("AnnotationSessions")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Annotator");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("Context.Entities.QuestionAnswer", b =>
                {
                    b.HasOne("Context.Entities.SegmentResponse", "SegmentResponse")
                        .WithMany("QuestionAnswers")
                        .HasForeignKey("SegmentResponseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SegmentResponse");
                });

            modelBuilder.Entity("Context.Entities.SegmentResponse", b =>
                {
                    b.HasOne("Context.Entities.AnnotationSession", "AnnotationSession")
                        .WithMany("SegmentResponses")
                        .HasForeignKey("AnnotationSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnnotationSession");
                });

            modelBuilder.Entity("Context.Entities.Video", b =>
                {
                    b.HasOne("Context.Entities.Admin", "UploadedByAdmin")
                        .WithMany("UploadedVideos")
                        .HasForeignKey("UploadedByAdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UploadedByAdmin");
                });

            modelBuilder.Entity("Context.Entities.Admin", b =>
                {
                    b.Navigation("UploadedVideos");
                });

            modelBuilder.Entity("Context.Entities.AnnotationSession", b =>
                {
                    b.Navigation("SegmentResponses");
                });

            modelBuilder.Entity("Context.Entities.Annotator", b =>
                {
                    b.Navigation("AnnotationSessions");
                });

            modelBuilder.Entity("Context.Entities.SegmentResponse", b =>
                {
                    b.Navigation("QuestionAnswers");
                });

            modelBuilder.Entity("Context.Entities.Video", b =>
                {
                    b.Navigation("AnnotationSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
